### ISSUE TITLE
Admin can see all orders and their status

### ISSUE THREAD

**Issue by janderson16** [alfosco/pog_hogs#31]
issueEighteen:
    title: Admin Orders
    body: >
      As an Admin
      When I visit the dashboard
      Then I can see a listing of all orders
      And I can see the total number of orders for each status **("Ordered", "Paid", "Cancelled", "Completed")**
      And I can see a link for each individual order
      And I can filter orders to display by each status type  **("Ordered", "Paid", "Cancelled", "Completed")**
      And I have links to transition between statuses
        - I can click on "cancel" on individual orders which are "paid" or "ordered"
        - I can click on "mark as paid" on orders that are "ordered"
        - I can click on "mark as completed" on orders that are "paid"

**Comment by maxglassie** [comment]
@ande1618 
- need to use strong params or it will cause things to break
- namespace orders under admin (admin:orders controller?) - break the logic into separate controllers
- admin should be able to see all the orders from across the site
- put logic into order for handling statuses (ex: "can_transition_to_cancelled?")
- status can be marked as complete - make model tests for these methods to use in the view
- use an enum for that
